DROP DOMAIN IF EXISTS ksuid CASCADE;
DROP DOMAIN IF EXISTS source CASCADE;
DROP DOMAIN IF EXISTS actor CASCADE;
DROP DOMAIN IF EXISTS component_array CASCADE;
DROP DOMAIN IF EXISTS component CASCADE;

CREATE DOMAIN ksuid AS VARCHAR(27);
CREATE DOMAIN source AS VARCHAR(30);
CREATE DOMAIN actor AS VARCHAR(20);
CREATE DOMAIN component AS JSONB;
CREATE DOMAIN component_array AS JSONB; -- Array<component>
